### ISSUE TITLE
transaction support for mysql connection not detected 

### ISSUE THREAD

**Issue by kumar303** [jbalogh/test-utils#14]
After upgrading playdoh to a newer test-utils we go this failure in our suite:

```
======================================================================
ERROR: test suite for <class 'tests.test__utils.AbsolutifyTests'>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/jenkins/jobs/playdoh-funfactory/workspace/.tox/py26/lib/python2.6/site-packages/nose/suite.py", line 208, in run
    self.setUp()
  File "/var/lib/jenkins/jobs/playdoh-funfactory/workspace/.tox/py26/lib/python2.6/site-packages/nose/suite.py", line 291, in setUp
    self.setupContext(ancestor)
  File "/var/lib/jenkins/jobs/playdoh-funfactory/workspace/.tox/py26/lib/python2.6/site-packages/nose/suite.py", line 314, in setupContext
    try_run(context, names)
  File "/var/lib/jenkins/jobs/playdoh-funfactory/workspace/.tox/py26/lib/python2.6/site-packages/nose/util.py", line 478, in try_run
    return func()
  File "/var/lib/jenkins/jobs/playdoh-funfactory/workspace/.playdoh/funtestapp/vendor/src/test-utils/test_utils/__init__.py", line 147, in setUpClass
    'capabilities.' % cls.__name__)
NotImplementedError: AbsolutifyTests supports only DBs with transaction capabilities.
```

The tests use mysql which should support a transaction, however `connections.all()[0].features.supports_transaction` is indeed None. Any ideas? Playdoh uses Django 1.3.1. I could also verify that `feature.confirm()` (which sets the transaction flag) had not been run but I don't know why.

**Comment by peterbe** [comment]
Haven't solved it but at least figured out one of the possible roots of the problem. The funfactory test running (invoked by tox) isn't calling the `confirm` method. 
https://github.com/jbalogh/test-utils/blob/master/test_utils/runner.py#L53
That's the one that's responsible for figuring out (amongst other things) if the current chosen database supports transactions. 

/me trying to figure out how the funfactory tests chose a runner and what can be done about that.

**Comment by kumar303** [comment]
oh! I forgot that the funfactory suite is not a django app, it's just a regular test suite that executes like `nosetests`. So the real problem here is that the Django test runner (and thus the radical test runner) is not getting executed. This issue can be closed.
