### ISSUE TITLE
initial_data fixture breaks FORCE_DB=0 test cases with mysql 5.6.10

### ISSUE THREAD

**Issue by Pike** [jbalogh/test-utils#22]
I've created a playdoh fork to demonstrate this, https://github.com/Pike/initial-data-fail

The test passes without the initial data, but once you update to the latest iteration, and FORCE_DB=1 once, you have the initial data in the test database, but apparently, the auto increment stuff isn't hooked up right.

I wonder if this is related to the changes around innodb and auto increment.

CC @Sheeri and @peterbe, as I'm seeing this on elmo now, too.

**Comment by Pike** [comment]
Forgot the actual error, the new object created by the test conflicts with the pre-existing fixture data:

(funfactory)ahecht-16514:ample ahecht$ ./manage.py test
nosetests --verbosity 1
Reusing old database "test_playdoh_app". Set env var FORCE_DB=1 if you need fresh DBs.

# E

## ERROR: test_thingie (ample.base.tests.ThingieTestCase)

Traceback (most recent call last):
  File "/src/webdev/funfactory/src/ample/ample/base/tests.py", line 7, in test_thingie
    thing = Thingie.objects.get_or_create(name="foo")
  File "/src/webdev/funfactory/src/ample/vendor/lib/python/django/db/models/manager.py", line 134, in get_or_create
    return self.get_query_set().get_or_create(*_kwargs)
  File "/src/webdev/funfactory/src/ample/vendor/lib/python/django/db/models/query.py", line 452, in get_or_create
    obj.save(force_insert=True, using=self.db)
  File "/src/webdev/funfactory/src/ample/vendor/lib/python/django/db/models/base.py", line 463, in save
    self.save_base(using=using, force_insert=force_insert, force_update=force_update)
  File "/src/webdev/funfactory/src/ample/vendor/lib/python/django/db/models/base.py", line 551, in save_base
    result = manager._insert([self], fields=fields, return_id=update_pk, using=using, raw=raw)
  File "/src/webdev/funfactory/src/ample/vendor/lib/python/django/db/models/manager.py", line 203, in _insert
    return insert_query(self.model, objs, fields, *_kwargs)
  File "/src/webdev/funfactory/src/ample/vendor/lib/python/django/db/models/query.py", line 1593, in insert_query
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/src/webdev/funfactory/src/ample/vendor/lib/python/django/db/models/sql/compiler.py", line 912, in execute_sql
    cursor.execute(sql, params)
  File "/src/webdev/funfactory/src/ample/vendor/lib/python/django/db/backends/mysql/base.py", line 114, in execute
    return self.cursor.execute(query, args)
  File "/src/webdev/funfactory/lib/python2.7/site-packages/MySQLdb/cursors.py", line 173, in execute
    self.errorhandler(self, exc, value)
  File "/src/webdev/funfactory/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
IntegrityError: (1062, "Duplicate entry '1' for key 'PRIMARY'")

---

Ran 1 test in 0.058s

**Comment by jsocol** [comment]
Are you setting FORCE_DB=0 the very first time you run the tests?

The data in the fixture explicitly sets a PK, so it's not a problem with auto-increment. It looks like with FORCE_DB=0 it's trying to install the fixture over an already-populated table.

**Comment by Pike** [comment]
You can permute things at will, FORCE_DB=1 tests pass, =0 fail. Each N times after each other.

The error is also not installing the fixture, but creating the first non-fixture object, which tries to get PK=1, but that's taken in the db.

**Comment by Pike** [comment]
Updated to 5.6.13, and things work now. Closing. I didn't try to actually find an upstream bug report on this.
